platform :ios, '16.4'

target 'MovieApplication' do
  use_frameworks!

  pod 'SwiftGen', '~> 6.0'
  pod 'SwiftLint'
  pod 'Kingfisher', '~> 7.0'
  pod 'Moya', '~> 15.0'

end

post_install do |installer|
   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 16.4
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
        end
     end
   end
end
